import './globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import Navbar from './components/Navbar'

const inter = Roboto({subsets: ['latin'], weight: ['300', '100', '400', '500', '700', '900'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
           {/* NAVIGATION BAR */}
           <div className="fixed w-full"> <Navbar /></div>
        
        {children}
        </body>
    </html>
  )
}
